# Generated by Django 3.2.7 on 2022-02-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('court_costs', models.FloatField(default=0, verbose_name='koszty sądowe')),
                ('clause_costs', models.FloatField(null=True, verbose_name='koszty klauzuli')),
                ('interest', models.FloatField(null=True, verbose_name='odsetki')),
                ('attorney_representation_costs', models.FloatField(null=True, verbose_name='koszty zast. w egz')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.case', verbose_name='klauzula sprawy')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(null=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.refund')),
            ],
        ),
    ]
