# Generated by Django 3.2.4 on 2023-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20230118_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateField(null=True, verbose_name='data spłaty'),
        ),
    ]
