# Generated by Django 3.2.7 on 2022-02-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bailiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='sygnatura kancelarii')),
                ('type', models.CharField(blank=True, choices=[('eviction', 'eksmisja'), ('payment', 'o zapłatę'), ('divorce', 'rozwód'), ('insolvency', 'zgłoszenie wierzytenlość')], default=None, max_length=60, null=True, verbose_name='typ sprawy')),
                ('result', models.CharField(blank=True, max_length=60, null=True, verbose_name='wynik sprawy')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('costs', models.FloatField(blank=True, default=0, null=True, verbose_name='koszty sprawy')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='opis')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='pełna nazwa podmiotu gospodarczego')),
                ('nip', models.IntegerField(blank=True, null=True, verbose_name='nip')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='notatki')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Firstnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60, unique=True, verbose_name='imię')),
                ('gender', models.CharField(blank=True, choices=[('male', 'mężczyzna'), ('female', 'kobieta')], default=None, max_length=60, null=True, verbose_name='płeć')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='imię')),
                ('last_name', models.CharField(max_length=60, null=True, verbose_name='nazwisko')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, verbose_name='numer pesel')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='adres')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='numer telefonu')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=30, null=True, verbose_name='notatka')),
            ],
        ),
        migrations.AddIndex(
            model_name='firstnames',
            index=models.Index(fields=['name'], name='register_fi_name_00abb3_idx'),
        ),
        migrations.AddField(
            model_name='family',
            name='persons',
            field=models.ManyToManyField(to='register.Person'),
        ),
        migrations.AddField(
            model_name='case',
            name='accused_companies',
            field=models.ManyToManyField(related_name='accused_companies', to='register.Company'),
        ),
        migrations.AddField(
            model_name='case',
            name='accused_persons',
            field=models.ManyToManyField(related_name='accused_persons', to='register.Person', verbose_name='osoby oskarżone w sprawie'),
        ),
        migrations.AddField(
            model_name='case',
            name='bailiff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.bailiff', verbose_name='komornik'),
        ),
        migrations.AddField(
            model_name='case',
            name='prosecutor_companies',
            field=models.ManyToManyField(related_name='prosecutor_companies', to='register.Company'),
        ),
        migrations.AddField(
            model_name='case',
            name='prosecutor_persons',
            field=models.ManyToManyField(related_name='prosecutor_persons', to='register.Person'),
        ),
    ]
