# Generated by Django 3.2.7 on 2021-09-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bailiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('persons', models.ManyToManyField(to='register.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('eksmisja', 'wypedzenie'), ('morderstwo', 'zbrodnia')], max_length=60)),
                ('result', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('costs', models.FloatField(null=True)),
                ('bailiff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.bailiff')),
            ],
        ),
    ]
