# Generated by Django 3.2.4 on 2022-09-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='costs',
        ),
        migrations.AddField(
            model_name='case',
            name='court_reference_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='sygnatura sądowa'),
        ),
    ]
