# Generated by Django 3.2.4 on 2022-09-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20220913_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='count_reference_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
