# Generated by Django 3.2.7 on 2021-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210918_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='date_created',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='date_created',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='case',
            name='signature',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='sygnatura kancelarii'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('eviction ', 'eksmisja'), ('murder', 'morderstwo')], max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='adres'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_last',
            field=models.CharField(max_length=60, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='notatka'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='numer telefonu'),
        ),
    ]
