# Generated by Django 3.2.7 on 2021-09-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210918_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_last',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='case',
            name='signature',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='sygnatura kancelarii'),
        ),
    ]
