# Generated by Django 3.2.4 on 2022-10-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_case_count_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.IntegerField()),
                ('signature', models.CharField(max_length=15)),
                ('court_name', models.CharField(max_length=150)),
                ('receipt_date', models.DateTimeField(verbose_name='data wpłynięcia sprawy')),
                ('finish_date', models.DateTimeField(verbose_name='data zakończenia rozprawy')),
                ('judge_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
