# Generated by Django 3.2.7 on 2021-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210920_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='persons',
            field=models.ManyToManyField(to='register.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='result',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='wynik sprawy'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(blank=True, choices=[('eviction ', 'eksmisja'), ('murder', 'morderstwo')], max_length=60, null=True, verbose_name='typ sprawy'),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
