# Generated by Django 3.2.4 on 2022-11-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='court_reference_number',
        ),
        migrations.AddField(
            model_name='case',
            name='cort',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.court', verbose_name='komornik'),
        ),
    ]
