# Generated by Django 3.2.4 on 2022-11-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20221117_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='cort',
            new_name='court',
        ),
        migrations.RemoveField(
            model_name='case',
            name='count_reference_id',
        ),
    ]
