# Generated by Django 3.2.7 on 2021-10-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20211018_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='bailiff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.bailiff'),
        ),
        migrations.AlterField(
            model_name='case',
            name='costs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='signature',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='sygnatura kancelarii'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(blank=True, choices=[('eviction', 'eksmisja'), ('murder', 'morderstwo')], default=None, max_length=60, null=True, verbose_name='typ sprawy'),
        ),
    ]
