# Generated by Django 3.2.7 on 2021-11-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20211018_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='pełna nazwa podmiotu gospodarczego')),
                ('nip', models.IntegerField(blank=True, null=True, verbose_name='nip')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='notatki')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='companies',
            field=models.ManyToManyField(to='register.Company'),
        ),
    ]
