# Generated by Django 3.2.4 on 2022-11-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20221117_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
