# Generated by Django 3.2.7 on 2021-11-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20211112_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='opis'),
        ),
    ]
