# Generated by Django 3.2.4 on 2022-12-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20221117_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailiff',
            name='city',
            field=models.CharField(default='Grudziądz', max_length=60),
        ),
        migrations.AddField(
            model_name='bailiff',
            name='postcode',
            field=models.CharField(default='86-300', max_length=60),
        ),
        migrations.AddField(
            model_name='bailiff',
            name='street',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='court',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.case', verbose_name='sprawa'),
        ),
    ]
