# Generated by Django 3.2.7 on 2021-11-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_case_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='imię')),
                ('gender', models.CharField(blank=True, choices=[('male', 'mężczyzna'), ('female', 'kobieta')], default=None, max_length=60, null=True, verbose_name='płeć')),
            ],
        ),
    ]
