# Generated by Django 3.2.7 on 2021-11-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_firstnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstnames',
            name='name',
            field=models.CharField(default=None, max_length=60, unique=True, verbose_name='imię'),
        ),
    ]
