# Generated by Django 3.2.4 on 2022-12-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_case_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='Grudziądz', max_length=60, verbose_name='miejscowość'),
        ),
        migrations.AddField(
            model_name='person',
            name='postcode',
            field=models.CharField(default='86-300', max_length=60, verbose_name='kod pocztowy'),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(default='', max_length=60, verbose_name='ulica'),
        ),
        migrations.AlterField(
            model_name='bailiff',
            name='city',
            field=models.CharField(default='Grudziądz', max_length=60, verbose_name='miejscowość'),
        ),
        migrations.AlterField(
            model_name='bailiff',
            name='postcode',
            field=models.CharField(default='86-300', max_length=60, verbose_name='kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='bailiff',
            name='street',
            field=models.CharField(default='', max_length=60, verbose_name='ulica'),
        ),
    ]
