# Generated by Django 3.2.7 on 2021-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_firstnames_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='firstnames',
            index=models.Index(fields=['name'], name='register_fi_name_00abb3_idx'),
        ),
    ]
