# Generated by Django 3.2.4 on 2023-02-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20221208_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailiff',
            name='name',
            field=models.CharField(max_length=60, verbose_name='imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='court',
            name='finish_date',
            field=models.DateTimeField(null=True, verbose_name='data zakończenia rozprawy'),
        ),
    ]
