# Generated by Django 3.2.7 on 2022-01-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_firstnames_register_fi_name_00abb3_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='value',
        ),
        migrations.AddField(
            model_name='person',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='numer pesel'),
        ),
        migrations.AddField(
            model_name='refund',
            name='attorney_representation_costs',
            field=models.FloatField(null=True, verbose_name='koszty zast. w egz'),
        ),
        migrations.AddField(
            model_name='refund',
            name='clause_costs',
            field=models.FloatField(null=True, verbose_name='koszty klauzuli'),
        ),
        migrations.AddField(
            model_name='refund',
            name='court_costs',
            field=models.FloatField(default=0, verbose_name='koszty sądowe'),
        ),
        migrations.AddField(
            model_name='refund',
            name='interest',
            field=models.FloatField(null=True, verbose_name='odsetki'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(blank=True, choices=[('eviction', 'eksmisja'), ('payment', 'o zapłatę'), ('divorce', 'rozwód'), ('insolvency', 'zgłoszenie wierzytenlość')], default=None, max_length=60, null=True, verbose_name='typ sprawy'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=60, null=True, verbose_name='nazwisko'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.case', verbose_name='klauzula sprawy'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(null=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.refund')),
            ],
        ),
    ]
