# Generated by Django 3.2.4 on 2023-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20230203_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nazwa rodziny'),
        ),
        migrations.AlterField(
            model_name='family',
            name='persons',
            field=models.ManyToManyField(to='register.Person', verbose_name='członkowie rodziny'),
        ),
    ]
