# Generated by Django 3.2.4 on 2023-02-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20230212_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='krs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='nip',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='nip'),
        ),
    ]
