# Generated by Django 3.2.4 on 2023-02-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20230213_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailiff',
            name='office_name',
            field=models.CharField(default='', max_length=200, verbose_name='nazwa kancelarii'),
        ),
    ]
