# Generated by Django 3.2.4 on 2023-03-06 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_bailiff_office_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='accused_companies',
            field=models.ManyToManyField(blank=True, related_name='accused_companies', to='register.Company'),
        ),
        migrations.AlterField(
            model_name='case',
            name='prosecutor_companies',
            field=models.ManyToManyField(blank=True, related_name='prosecutor_companies', to='register.Company'),
        ),
        migrations.AlterField(
            model_name='case',
            name='prosecutor_persons',
            field=models.ManyToManyField(blank=True, related_name='prosecutor_persons', to='register.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='result',
            field=models.CharField(choices=[('new', 'nowa'), ('begin', 'rozpoczęta'), ('won', 'wygrana'), ('lose', 'przegrana'), ('enforced', 'egzekwowana'), ('end', 'zakończona')], default='new', max_length=60, verbose_name='wynik: sprawy'),
        ),
        migrations.AlterField(
            model_name='court',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court', to='register.case', verbose_name='sprawa'),
        ),
        migrations.AlterField(
            model_name='court',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data zakończenia rozprawy'),
        ),
        migrations.AlterField(
            model_name='court',
            name='receipt_date',
            field=models.DateTimeField(null=True, verbose_name='data wpłynięcia sprawy'),
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='notatka'),
        ),
    ]
